### ISSUE TITLE
Running this example without making any changes returns "Internal Error!"

### ISSUE THREAD

**Issue by 3267xiao** [android/privacy-sandbox-samples#12]
![Snipaste_2022-07-29_12-08-29](https://user-images.githubusercontent.com/30384650/181681083-9eaa38b0-db49-453c-a773-1e43911e4972.png)

**Comment by cshmerling** [comment]
What revision of device emulator image are you using? There were some breaking changes to the API introduced in the latest release so would like to confirm you are using the latest version

**Comment by cshmerling** [comment]
@3267xiao going to try once more to get some more information:

1. What revision of the SDK are you running?
2. What revision of the emulator images is installed on your device?
3. When starting the app, did you follow the steps in the [Testing](https://github.com/android/privacy-sandbox-samples/blob/main/TopicsJava/README.md#testing) section of the README?
4. If you can repro the issue consistently, can you capture an `adb bugreport` and upload it to our [IssueTracker](https://issuetracker.google.com/issues/new?component=1116743&template=1629474)

If I don't get a response in a few more days I will close this issue due to inactivity

**Comment by cshmerling** [comment]
Marking this as resolved due to inactivity
