### ISSUE TITLE
Running this example without making any changes returns " FAILED BINDER TRANSACTION"

### ISSUE THREAD

**Issue by lpz1096** [android/privacy-sandbox-samples#13]
![image](https://user-images.githubusercontent.com/37067547/181915524-7ac7110b-e4f0-4659-a898-7169c53ee812.png)

**Comment by Barbicannn** [comment]
U

**Comment by cshmerling** [comment]
Thanks for the feedback- I'll start looking in to this. In order to help me out, can you answer the following:
1. What revision of the SDK are you running?
2. What revision of the emulator images is installed on your device?
3. When starting the app, did you follow the steps in the [Testing](https://github.com/android/privacy-sandbox-samples/blob/main/TopicsJava/README.md#testing) section of the README?

**Comment by cshmerling** [comment]
@lpz1096 can you provide any updates based on my last comment? Otherwise I'd suggest making sure you have updated everything to the latest versions (device emulator image, SDK). If I don't get a response for a couple more days I will close this issue due to inactivity

**Comment by lpz1096** [comment]
I restarted the computer and reconfigured the environment.thinks

**Comment by cshmerling** [comment]
Great, closing this issue then.

Thanks for trying things out!
