### ISSUE TITLE
Protected Audience : Waterfall Mediation queries

### ISSUE THREAD

**Issue by pm-vishal-chougule** [android/privacy-sandbox-samples#96]
I was exploring the protected audience APIs for the Waterfall mediation use case and I have a couple of queries that are mentioned below.

1. How the 3P SDK network invocation will happen from Mediation SDK?  (Traditionally it is used to happen through Reflection API) Is there any plan to handle the same case?
2. The current document and developer guide describe the ad rendering is going to be handled by Mediation SDK, so in that case 3P SDKs will lose the ad rendering capability which contains a lot of custom implementations like UI-specific details, OM SDK implementation, etc. Is there any rationale behind not allowing 3P SDKs to render their own ads?
   
I think we should reconsider this approach, should allow 3P SDK to render its own ads. Please share your thoughts on this?

**Comment by cshmerling** [comment]
For an on device auction, the mediation SDK will need to know which 3P SDKs it is working with and will need to invoke those SDKs directly. However, since this question is pretty old and a lot has changes about the Protected Audience landscape in this time, I would suggest taking a look at [server-orchestrated multi-seller auctions](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_multi_seller_auctions.md#server-orchestrated-component-auction) as this flow might be more applicable.

We have heard the feedback regarding expecting the mediation SDK to render the ad, and we are looking in to alternative solutions where the 3P SDK that owns the ad can do the rendering. We will provide updates on the explainer as this develops.
